language: php
sudo: false

matrix:
  include:
    - php: "5.3"
      env: USE_PSALM=0
    - php: "5.4"
      env: USE_PSALM=0
    - php: "5.5"
      env: USE_PSALM=1
    - php: "5.6"
      env: USE_PSALM=1
    - php: "7.0"
      env: USE_PSALM=1
    - php: "7.1"
      env: USE_PSALM=1

matrix:
    fast_finish: true

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
