language: php
sudo: false

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"

matrix:
    fast_finish: true

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
    - if [[ [ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ] || [ ${TRAVIS_PHP_VERSION:0:1} == "7" ] ]]; then; vendor/bin/psalm; fi
